# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23d12c244eddeb40adf8eb9aa15dbb64e2dce50d87be91a0b22ec2f39e79e8518d9f3f92f42f2ecc401b11a4f78f48ec705f2f26eef2059ebc44f3192a4aefe5

test:
  secret_key_base: cd7f091b7a98c3605965167a7ee9e9cebc480b917c30a28c72f714dd747611b09bdff5215820a47ca69ae15fc9950d54af6cfa87e767f0adf5cb6af17e6965f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
